name: Chromatic

on:
  pull_request:
    branches:
      - main
  # workflow_call:
  #   inputs:
  #     app-name:
  #       description: "Name of the app"
  #       required: true
  #       type: string
  #     chromatic-token:
  #       description: "Chromatic project token"
  #       required: true
  #       type: string
  #     path:
  #       description: "Working directory of the project"
  #       required: true
  #       type: string

jobs:
  chromatic:
    name: Run Chromatic checks for all apps
    strategy:
      matrix:
        app:
          - name: component-library
            chromatic-token: ${{ github.env.component-library }}
            path: apps/component-library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Build storybook
        run: pnpm build-storybook --filter ${{ matrix.app.name }}

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          exitOnceUploaded: true
          onlyChanged: true
          projectToken: ${{ matrix.app.chromatic-token }}
          storybookBuildDir: storybook-static
          workingDir: ${{ matrix.app.path }}
